### ISSUE TITLE
Can we pull multiple ledgers?

### ISSUE THREAD

**Issue by Gowtamd** [dhananjay1405/excelkida-power-query-library#2]
Hi Sir,

Thanks a lot for the wonderful code.

Can we pull data from multiple ledgers using this code. How should the code be modified, if yes

**Comment by dhananjay1405** [comment]
Unfortunately this code can pull data for only 1 ledger at a time.
Power Query supports running a loop. In that approach, you will have to convert this Power Query into a function, which accepts ledger name as parameter & then setup another Power Query, which will keep on calling this main query. If you want to know how to run loop via Power Query, you will find a implementation in gst folder of this project, where I have created 2 files (refer below files on this project)
[fn-gstn-info.pq](https://github.com/dhananjay1405/excelkida-power-query-library/blob/master/gst/fn-gstn-info.pq)
[gstr-1-b2b-json-consolidate.pq](https://github.com/dhananjay1405/excelkida-power-query-library/blob/master/gst/gstr-1-b2b-json-consolidate.pq)

Refer functions Table.Combine() and List.Generate() which I have used to run a loop & accumulated result. You can do similar thing for Tally. To start with, you can prepare an array of 4-5 ledger names & develop it

**Comment by Gowtamd** [comment]
Thanks a lot sir for your response. Would be happy to have  a code from that incorporates my request. Is this a SQL query sir? I know to code in VBA. Can i build a code on the lines of a VBA code?
