### ISSUE TITLE
Issue in fetching data.

### ISSUE THREAD

**Issue by Deepakca-IT** [dhananjay1405/excelkida-power-query-library#4]
Hi sir.First of all need to thank you for providing these codes.

I have been using it to fetch ledger wise vouchers from tally ERP 9.If the voucher number in tally is blank then the final data output comes as an error.
How to resolve?
Thanks in advance.

**Comment by gellavenugopal** [comment]
Hi Deppak

 

You should be capturing the Guid of the voucher to over come this issue.

 

 

Regards

Venugopal. G

**Comment by Deepakca-IT** [comment]
> Hi Deppak You should be capturing the Guid of the voucher to over come this issue. Regards Venugopal. G

Thank you sir.
